version: "3.8"

services:
  localstack:
    container_name: surt-localstack
    image: localstack/localstack
    network_mode: bridge
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=s3
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "${PWD}/surtcfg.sh:/docker-entrypoint-initaws.d/surtcfg.sh"
      - "${PWD}/testdata/test.txt:/testdata/test.txt"
