before:
  hooks:
    - go mod download
builds:
  - id: surt-api
    binary: surt-api
    main: ./cmd/surt-api
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: surt-task-runner
    binary: surt-task-runner
    main: ./cmd/surt-task-runner
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
